# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: taskify-pool

stages:
- stage: build 
  displayName: mvn_build
  jobs:
  -  job: 
     displayName: mvn-build
     steps: 
     - task: PowerShell@2
       inputs:
         targetType: 'inline'
         script: |
           cd "$(Build.SourcesDirectory)\JavaLoginPracticeApp-main\JavaLoginPracticeApp-main"
               dir
               mvn clean install

     - task: CopyFiles@2
       inputs:
        SourceFolder: '$(Build.SourcesDirectory)\JavaLoginPracticeApp-main\JavaLoginPracticeApp-main\target'
        Contents: '*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

         
     - task: PublishBuildArtifacts@1
       inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'build'
          publishLocation: 'Container'

 # ---------------- DEPLOY ----------------

- stage: deploy
  displayName: tomcat_deploy

  dependsOn: build

  jobs:
  - job:
    displayName: deploy-war

    steps:

    - download: current
      artifact: build

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |

          # Stop Tomcat

          cd "C:\Tomcat\bin"

          .\shutdown.bat

          Start-Sleep -Seconds 10

          # Copy WAR

          Copy-Item "$(Pipeline.Workspace)\build\*.war" "C:\Tomcat\webapps\" -Force

          # Start Tomcat

          .\startup.bat 
