trigger: none

pool:
  name: taskify-pool

stages:

# ================= BUILD STAGE =================

- stage: build
  displayName: Maven_Build

  jobs:
  - job: BuildJob
    displayName: MavenBuild

    steps:

    - checkout: self

    - task: PowerShell@2
      displayName: Maven Build
      inputs:
        targetType: 'inline'
        script: |

          cd "$(Build.SourcesDirectory)\JavaLoginPracticeApp-main\JavaLoginPracticeApp-main"

          dir

          mvn clean install

    # Copy WAR File

    - task: CopyFiles@2
      displayName: Copy WAR File
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\JavaLoginPracticeApp-main\JavaLoginPracticeApp-main\target'
        Contents: '*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    # Publish Artifact

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'build'
        publishLocation: 'Container'

# ================= SAST + SCA SCANNING =================

- stage: scanning
  displayName: Security_Scanning

  dependsOn: build

  jobs:
  - job: SecurityScan
    displayName: Sonar_and_OWASP

    steps:

    - checkout: self

    # ================= SONARQUBE SAST =================

    - task: PowerShell@2
      displayName: SonarQube SAST Scan
      inputs:
        targetType: 'inline'
        script: |

          cd "$(Build.SourcesDirectory)\JavaLoginPracticeApp-main\JavaLoginPracticeApp-main"

          sonar-scanner `
          -"Dsonar.projectKey=java-login" `
          -"Dsonar.sources=." `
          -"Dsonar.host.url=http://localhost:9000" `
          -"Dsonar.login=admin" `
          -"Dsonar.token=sqa_8dec0989250f254c523cd120764eeaf1a02f7f5c"

    # ================= OWASP SCA =================

    - task: PowerShell@2
      displayName: OWASP Dependency Check
      inputs:
        targetType: 'inline'
        script: |

          cd "$(Build.SourcesDirectory)\JavaLoginPracticeApp-main\JavaLoginPracticeApp-main"

          dependency-check.bat `
          --project "JavaLoginPracticeApp" `
          --scan . `
          --format HTML `
          --out reports

# ================= DEPLOY STAGE =================

- stage: deploy
  displayName: Tomcat_Deploy

  dependsOn: scanning

  jobs:
  - job: DeployWAR
    displayName: Deploy_To_Tomcat

    steps:

    - download: current
      artifact: build

    - task: PowerShell@2
      displayName: Deploy WAR To Tomcat
      inputs:
        targetType: 'inline'
        script: |

          # Stop Tomcat

          cd "C:\tools\apache-tomcat-10.1.55\bin"

          .\shutdown.bat

          Start-Sleep -Seconds 10

          # Remove Old WAR (Optional)

          Remove-Item "C:\tools\apache-tomcat-10.1.55\webapps\*.war" -Force -ErrorAction SilentlyContinue

          # Copy New WAR

          Copy-Item "$(Pipeline.Workspace)\build\*.war" "C:\tools\apache-tomcat-10.1.55\webapps\" -Force

          # Start Tomcat

          .\startup.bat